version: '2'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"

  api:
    build: ./api/
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db

  html:
    build: ./html/
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on: 
      - api 
    links:
      - api:api
    

